Repository trento-project/ansible, pull requests merged in 2024-02, with the labels that each got.

#23 Fix default secret key rendering
  roles/containers/defaults/main.yml
Labels: bug

#24 Enable alerting
  README.md
  roles/containers/defaults/main.yml
  roles/containers/tasks/main.yml
Labels: documentation, enhancement

#25 Improve log message for verify alerting env's step
  roles/containers/tasks/main.yml
Labels: enhancement

#26 Add Apache license
  LICENSE
Labels: documentation, enhancement

#27 Fix nginx_vhost_filename and rabbitmq_vhost usage
  README.md
  roles/agent/defaults/main.yml
  roles/agent/tasks/main.yml
  roles/proxy/defaults/main.yml
Labels: bug
